<?php

namespace App\Filament\Resources\Destinations\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\ImageEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class DestinationInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('id')
                    ->label('ID'),
                TextEntry::make('slug'),
                TextEntry::make('title'),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('short_description')
                    ->placeholder('-'),
                TextEntry::make('category'),
                TextEntry::make('location'),
                TextEntry::make('county')
                    ->placeholder('-'),
                TextEntry::make('region')
                    ->placeholder('-'),
                TextEntry::make('country'),
                TextEntry::make('latitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('longitude')
                    ->numeric()
                    ->placeholder('-'),
                ImageEntry::make('cover_image_url')
                    ->placeholder('-'),
                TextEntry::make('gallery')
                    ->columnSpanFull(),
                TextEntry::make('price_kes')
                    ->numeric(),
                TextEntry::make('price_usd')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rating')
                    ->numeric(),
                TextEntry::make('review_count')
                    ->numeric(),
                TextEntry::make('duration_days')
                    ->numeric(),
                TextEntry::make('duration_label'),
                TextEntry::make('group_size_max')
                    ->numeric(),
                TextEntry::make('difficulty'),
                TextEntry::make('tour_type'),
                TextEntry::make('highlights')
                    ->columnSpanFull(),
                TextEntry::make('included')
                    ->columnSpanFull(),
                TextEntry::make('excluded')
                    ->columnSpanFull(),
                TextEntry::make('what_to_bring')
                    ->columnSpanFull(),
                TextEntry::make('languages_spoken')
                    ->columnSpanFull(),
                TextEntry::make('meeting_point')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('meeting_lat')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('meeting_lng')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('transport_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('meal_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('health_safety_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('cancellation_policy')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('faqs')
                    ->columnSpanFull(),
                TextEntry::make('operator.name')
                    ->label('Operator')
                    ->placeholder('-'),
                IconEntry::make('is_popular')
                    ->boolean(),
                IconEntry::make('is_featured')
                    ->boolean(),
                IconEntry::make('is_active')
                    ->boolean(),
                TextEntry::make('xp_reward')
                    ->numeric(),
                TextEntry::make('metadata')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('locationNode.name')
                    ->label('Location node')
                    ->placeholder('-'),
                TextEntry::make('busyness_score')
                    ->numeric(),
                TextEntry::make('crowd_density'),
                TextEntry::make('current_visitors')
                    ->numeric(),
                TextEntry::make('peak_hours')
                    ->placeholder('-'),
                TextEntry::make('weather_note')
                    ->placeholder('-'),
                IconEntry::make('instant_booking')
                    ->boolean(),
                TextEntry::make('available_days')
                    ->placeholder('-')
                    ->columnSpanFull(),
            ]);
    }
}
