<?php

namespace App\Filament\Resources\Users\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class UserForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('phone_number')
                    ->tel()
                    ->default(null),
                TextInput::make('first_name')
                    ->default(null),
                TextInput::make('last_name')
                    ->default(null),
                TextInput::make('username')
                    ->default(null),
                TextInput::make('display_name')
                    ->default(null),
                DatePicker::make('date_of_birth'),
                Textarea::make('bio')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('photo_url')
                    ->url()
                    ->default(null),
                TextInput::make('photo_thumbnail_url')
                    ->url()
                    ->default(null),
                TextInput::make('gender')
                    ->default(null),
                TextInput::make('nationality')
                    ->default(null),
                TextInput::make('home_country')
                    ->default(null),
                TextInput::make('referral_source')
                    ->default(null),
                TextInput::make('id_number')
                    ->default(null),
                TextInput::make('passport_number')
                    ->default(null),
                Textarea::make('address')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('city')
                    ->default(null),
                TextInput::make('country')
                    ->required()
                    ->default('Kenya'),
                TextInput::make('postal_code')
                    ->default(null),
                Textarea::make('interests')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('languages')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('travel_styles')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('activity_preferences')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('dietary_restrictions')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('accessibility_needs')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('preferred_currency')
                    ->required()
                    ->default('KES'),
                Toggle::make('email_notifications')
                    ->required(),
                Toggle::make('sms_notifications')
                    ->required(),
                Toggle::make('push_notifications')
                    ->required(),
                Toggle::make('location_enabled')
                    ->required(),
                Toggle::make('show_distance_away')
                    ->required(),
                TextInput::make('emergency_contact_name')
                    ->default(null),
                TextInput::make('emergency_contact_phone')
                    ->tel()
                    ->default(null),
                TextInput::make('emergency_contact_relation')
                    ->default(null),
                TextInput::make('travel_style')
                    ->default(null),
                Toggle::make('travel_insurance')
                    ->required(),
                TextInput::make('explorer_level')
                    ->required()
                    ->default('explorer'),
                TextInput::make('current_xp')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('streak_days')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('unlocked_badges')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('role')
                    ->required()
                    ->default('traveler'),
                TextInput::make('profile_completion')
                    ->required()
                    ->numeric()
                    ->default(0),
                Toggle::make('is_profile_public')
                    ->required(),
                Toggle::make('share_location_with_friends')
                    ->required(),
                DateTimePicker::make('phone_verified_at'),
                DateTimePicker::make('last_active_at'),
                TextInput::make('name')
                    ->required(),
                TextInput::make('email')
                    ->label('Email address')
                    ->email()
                    ->required(),
                TextInput::make('provider')
                    ->default(null),
                TextInput::make('provider_id')
                    ->default(null),
                DateTimePicker::make('email_verified_at'),
                TextInput::make('password')
                    ->password()
                    ->default(null),
                Textarea::make('selectables')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('latitude')
                    ->numeric()
                    ->default(null),
                TextInput::make('longitude')
                    ->numeric()
                    ->default(null),
                TextInput::make('current_activity')
                    ->default(null),
                TextInput::make('sharing_mode')
                    ->required()
                    ->default('off'),
                TextInput::make('traveller_status')
                    ->required()
                    ->default('offline'),
                DateTimePicker::make('last_seen_at'),
                Toggle::make('allow_dms')
                    ->required(),
                TextInput::make('gems_discovered_count')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }
}
