<?php

namespace App\Filament\Resources\Users\Schemas;

use App\Models\User;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class UserInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('phone_number')
                    ->placeholder('-'),
                TextEntry::make('first_name')
                    ->placeholder('-'),
                TextEntry::make('last_name')
                    ->placeholder('-'),
                TextEntry::make('username')
                    ->placeholder('-'),
                TextEntry::make('display_name')
                    ->placeholder('-'),
                TextEntry::make('date_of_birth')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('bio')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('photo_url')
                    ->placeholder('-'),
                TextEntry::make('photo_thumbnail_url')
                    ->placeholder('-'),
                TextEntry::make('gender')
                    ->placeholder('-'),
                TextEntry::make('nationality')
                    ->placeholder('-'),
                TextEntry::make('home_country')
                    ->placeholder('-'),
                TextEntry::make('referral_source')
                    ->placeholder('-'),
                TextEntry::make('id_number')
                    ->placeholder('-'),
                TextEntry::make('passport_number')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('city')
                    ->placeholder('-'),
                TextEntry::make('country'),
                TextEntry::make('postal_code')
                    ->placeholder('-'),
                TextEntry::make('interests')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('languages')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('travel_styles')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('activity_preferences')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('dietary_restrictions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('accessibility_needs')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('preferred_currency'),
                IconEntry::make('email_notifications')
                    ->boolean(),
                IconEntry::make('sms_notifications')
                    ->boolean(),
                IconEntry::make('push_notifications')
                    ->boolean(),
                IconEntry::make('location_enabled')
                    ->boolean(),
                IconEntry::make('show_distance_away')
                    ->boolean(),
                TextEntry::make('emergency_contact_name')
                    ->placeholder('-'),
                TextEntry::make('emergency_contact_phone')
                    ->placeholder('-'),
                TextEntry::make('emergency_contact_relation')
                    ->placeholder('-'),
                TextEntry::make('travel_style')
                    ->placeholder('-'),
                IconEntry::make('travel_insurance')
                    ->boolean(),
                TextEntry::make('explorer_level'),
                TextEntry::make('current_xp')
                    ->numeric(),
                TextEntry::make('streak_days')
                    ->numeric(),
                TextEntry::make('unlocked_badges')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('role'),
                TextEntry::make('profile_completion')
                    ->numeric(),
                IconEntry::make('is_profile_public')
                    ->boolean(),
                IconEntry::make('share_location_with_friends')
                    ->boolean(),
                TextEntry::make('phone_verified_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('last_active_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deleted_at')
                    ->dateTime()
                    ->visible(fn (User $record): bool => $record->trashed()),
                TextEntry::make('name'),
                TextEntry::make('email')
                    ->label('Email address'),
                TextEntry::make('provider')
                    ->placeholder('-'),
                TextEntry::make('provider_id')
                    ->placeholder('-'),
                TextEntry::make('email_verified_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('selectables')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('latitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('longitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('current_activity')
                    ->placeholder('-'),
                TextEntry::make('sharing_mode'),
                TextEntry::make('traveller_status'),
                TextEntry::make('last_seen_at')
                    ->dateTime()
                    ->placeholder('-'),
                IconEntry::make('allow_dms')
                    ->boolean(),
                TextEntry::make('gems_discovered_count')
                    ->numeric(),
            ]);
    }
}
