<?php

namespace App\Filament\Resources\HiddenGems\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\ImageEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class HiddenGemInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('id')
                    ->label('ID'),
                TextEntry::make('slug'),
                TextEntry::make('name'),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('short_description')
                    ->placeholder('-'),
                TextEntry::make('category'),
                TextEntry::make('type')
                    ->placeholder('-'),
                TextEntry::make('tags')
                    ->columnSpanFull(),
                TextEntry::make('location_name')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-'),
                TextEntry::make('city')
                    ->placeholder('-'),
                TextEntry::make('county')
                    ->placeholder('-'),
                TextEntry::make('region')
                    ->placeholder('-'),
                TextEntry::make('country'),
                TextEntry::make('latitude')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('longitude')
                    ->numeric()
                    ->placeholder('-'),
                ImageEntry::make('cover_image_url')
                    ->placeholder('-'),
                TextEntry::make('gallery')
                    ->columnSpanFull(),
                TextEntry::make('difficulty')
                    ->placeholder('-'),
                TextEntry::make('difficulty_level')
                    ->numeric(),
                TextEntry::make('best_time_to_visit')
                    ->placeholder('-'),
                TextEntry::make('entry_fee_citizens_kes')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('entry_fee_residents_kes')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('entry_fee_non_residents_usd')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('entry_fee_children_kes')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_free_entry')
                    ->boolean(),
                TextEntry::make('access_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('facilities')
                    ->columnSpanFull(),
                TextEntry::make('amenities')
                    ->columnSpanFull(),
                TextEntry::make('what_to_bring')
                    ->columnSpanFull(),
                TextEntry::make('best_for')
                    ->columnSpanFull(),
                TextEntry::make('transport_options')
                    ->columnSpanFull(),
                TextEntry::make('parking_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('contact_phone')
                    ->placeholder('-'),
                TextEntry::make('contact_email')
                    ->placeholder('-'),
                TextEntry::make('website')
                    ->placeholder('-'),
                TextEntry::make('operator.name')
                    ->label('Operator')
                    ->placeholder('-'),
                TextEntry::make('submitted_by_user_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rating')
                    ->numeric(),
                TextEntry::make('review_count')
                    ->numeric(),
                TextEntry::make('visitor_count')
                    ->numeric(),
                IconEntry::make('is_verified')
                    ->boolean(),
                IconEntry::make('is_featured')
                    ->boolean(),
                IconEntry::make('is_published')
                    ->boolean(),
                TextEntry::make('xp_reward')
                    ->numeric(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('audio_guide_url')
                    ->placeholder('-'),
                TextEntry::make('video_url')
                    ->placeholder('-'),
                TextEntry::make('discovered_by_count')
                    ->numeric(),
                TextEntry::make('upvotes')
                    ->numeric(),
                TextEntry::make('downvotes')
                    ->numeric(),
                TextEntry::make('added_by_name')
                    ->placeholder('-'),
                IconEntry::make('is_local_guide')
                    ->boolean(),
                TextEntry::make('verification_status'),
                TextEntry::make('locationNode.name')
                    ->label('Location node')
                    ->placeholder('-'),
                TextEntry::make('safety_notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('requires_permit')
                    ->boolean(),
                IconEntry::make('is_quest_unlock')
                    ->boolean(),
                TextEntry::make('accessibility')
                    ->placeholder('-')
                    ->columnSpanFull(),
            ]);
    }
}
