<?php

namespace App\Filament\Resources\HiddenGems\Schemas;

use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class HiddenGemForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('slug')
                    ->required(),
                TextInput::make('name')
                    ->required(),
                Textarea::make('description')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('short_description')
                    ->default(null),
                TextInput::make('category')
                    ->required(),
                TextInput::make('type')
                    ->default(null),
                Textarea::make('tags')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                TextInput::make('location_name')
                    ->default(null),
                TextInput::make('address')
                    ->default(null),
                TextInput::make('city')
                    ->default(null),
                TextInput::make('county')
                    ->default(null),
                TextInput::make('region')
                    ->default(null),
                TextInput::make('country')
                    ->required()
                    ->default('Kenya'),
                TextInput::make('latitude')
                    ->numeric()
                    ->default(null),
                TextInput::make('longitude')
                    ->numeric()
                    ->default(null),
                FileUpload::make('cover_image_url')
                    ->image(),
                Textarea::make('gallery')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                TextInput::make('difficulty')
                    ->default(null),
                TextInput::make('difficulty_level')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('best_time_to_visit')
                    ->default(null),
                TextInput::make('entry_fee_citizens_kes')
                    ->numeric()
                    ->default(null),
                TextInput::make('entry_fee_residents_kes')
                    ->numeric()
                    ->default(null),
                TextInput::make('entry_fee_non_residents_usd')
                    ->numeric()
                    ->default(null),
                TextInput::make('entry_fee_children_kes')
                    ->numeric()
                    ->default(null),
                Toggle::make('is_free_entry')
                    ->required(),
                Textarea::make('access_info')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('facilities')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                Textarea::make('amenities')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                Textarea::make('what_to_bring')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                Textarea::make('best_for')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                Textarea::make('transport_options')
                    ->required()
                    ->default('[]')
                    ->columnSpanFull(),
                Textarea::make('parking_info')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('contact_phone')
                    ->tel()
                    ->default(null),
                TextInput::make('contact_email')
                    ->email()
                    ->default(null),
                TextInput::make('website')
                    ->url()
                    ->default(null),
                Select::make('operator_id')
                    ->relationship('operator', 'name'),
                TextInput::make('submitted_by_user_id')
                    ->numeric()
                    ->default(null),
                TextInput::make('rating')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('review_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('visitor_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Toggle::make('is_verified')
                    ->required(),
                Toggle::make('is_featured')
                    ->required(),
                Toggle::make('is_published')
                    ->required(),
                TextInput::make('xp_reward')
                    ->required()
                    ->numeric()
                    ->default(150),
                TextInput::make('audio_guide_url')
                    ->url()
                    ->default(null),
                TextInput::make('video_url')
                    ->url()
                    ->default(null),
                TextInput::make('discovered_by_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('upvotes')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('downvotes')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('added_by_name')
                    ->default(null),
                Toggle::make('is_local_guide')
                    ->required(),
                TextInput::make('verification_status')
                    ->required()
                    ->default('pending'),
                Select::make('location_node_id')
                    ->relationship('locationNode', 'name'),
                Textarea::make('safety_notes')
                    ->default(null)
                    ->columnSpanFull(),
                Toggle::make('requires_permit')
                    ->required(),
                Toggle::make('is_quest_unlock')
                    ->required(),
                Textarea::make('accessibility')
                    ->default(null)
                    ->columnSpanFull(),
            ]);
    }
}
